/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Internal;

import Model.Internal.VoucherModel;
import Repository.Internal.BanHangRepo;
import Repository.Internal.VoucherRepo;
import View.Dialog.DiaLogInput;
import View.Dialog.DiaLogThongBao;
import View.Dialog.DiaLogYesNo;
import View.Panel.KhachHangPanel;
import View.Panel.VoucherPanel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lcinu
 */
public class BanHangInternal extends javax.swing.JInternalFrame {

    private BanHangRepo qLy = new BanHangRepo();
    private VoucherRepo voucherRepo = new VoucherRepo();
    private DiaLogThongBao thongBao = new DiaLogThongBao();
    
    private int idNhanVien;
    private int currentPage = 1;

    /**
     * Creates new form HomeInternal
     *
     * @param idNhanVien
     */
    public BanHangInternal(int idNhanVien) {
        initComponents();
        this.idNhanVien = idNhanVien;
        this.removeTitleBar();
        this.fillPanelSanPham();
        this.qLy.fillTableHoaDonCho(tblHoaDonCho);
        this.modelComboBox();
        this.showPopup(tblHoaDon);
        this.hovers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jblMaHoaDon = new javax.swing.JLabel();
        btChonKhachHang = new javax.swing.JButton();
        btnHuyKhachHang = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnVoucher = new javax.swing.JButton();
        btnApDung = new javax.swing.JButton();
        btnHuyVoucher = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTienMat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cbbThanhToan = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtChuyenKhoan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtTienDu = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnHoanTien = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        btnTaoHoaDon = new javax.swing.JButton();
        lblErrTtTm = new javax.swing.JLabel();
        lblErrTtCk = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonCho = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtSearchTenSanPham = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbbLoaiSanPham = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnPreSP = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnNextSP = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPopupMenu1.setAlignmentX(0.5F);
        jPopupMenu1.setAutoscrolls(true);
        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(150, 52));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/View/Tools.png"))); // NOI18N
        jMenuItem1.setText("Sửa số lượng");
        jMenuItem1.setToolTipText("");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.setIconTextGap(10);
        jMenuItem1.setMargin(new java.awt.Insets(3, 6, 3, 0));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/View/TrashCan.png"))); // NOI18N
        jMenuItem2.setText("Hủy chọn giày");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.setIconTextGap(10);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setBorder(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Mã Hóa Đơn:");

        jblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblMaHoaDon.setForeground(new java.awt.Color(51, 153, 255));
        jblMaHoaDon.setText("#####");

        btChonKhachHang.setBackground(new java.awt.Color(0, 153, 153));
        btChonKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btChonKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btChonKhachHang.setText("Chọn Khách Hàng");
        btChonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonKhachHangActionPerformed(evt);
            }
        });

        btnHuyKhachHang.setBackground(new java.awt.Color(0, 153, 153));
        btnHuyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyKhachHang.setText("Hủy");
        btnHuyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyKhachHangActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Tên Khách Hàng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("SĐT Khách Hàng:");

        txtTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Tổng Tiền:");

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("VNĐ");

        btnVoucher.setBackground(new java.awt.Color(0, 153, 153));
        btnVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnVoucher.setText("Voucher");
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });

        btnApDung.setBackground(new java.awt.Color(0, 153, 153));
        btnApDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApDung.setForeground(new java.awt.Color(255, 255, 255));
        btnApDung.setText("Áp Dụng");
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        btnHuyVoucher.setBackground(new java.awt.Color(0, 153, 153));
        btnHuyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyVoucher.setText("Hủy");
        btnHuyVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyVoucherActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Mã Voucher:");

        txtMaVoucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Giảm:");

        txtGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Thành Tiền:");

        txtThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("VNĐ");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Loại Thanh Toán:");

        txtTienMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTienMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienMatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienMatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienMatKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("VNĐ");

        cbbThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbbThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Chuyển Khoản", "Tiền Mặt và Chuyển Khoản" }));
        cbbThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbThanhToanMouseClicked(evt);
            }
        });
        cbbThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThanhToanActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tiền Mặt:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Chuyển Khoản:");

        txtChuyenKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChuyenKhoan.setEnabled(false);
        txtChuyenKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChuyenKhoanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChuyenKhoanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChuyenKhoanKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("VNĐ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Tiền Dư:");

        txtTienDu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("VNĐ");

        btnHoanTien.setBackground(new java.awt.Color(0, 153, 153));
        btnHoanTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoanTien.setForeground(new java.awt.Color(255, 255, 255));
        btnHoanTien.setText("Trả Lại");
        btnHoanTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanTienActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(0, 153, 153));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setBackground(new java.awt.Color(0, 153, 153));
        btnInHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnInHoaDon.setText("In Hóa Đơn");
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        btnTaoHoaDon.setBackground(new java.awt.Color(0, 153, 153));
        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHoaDon.setText("Tạo Hóa Đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        lblErrTtTm.setForeground(new java.awt.Color(255, 0, 0));
        lblErrTtTm.setText(" ");

        lblErrTtCk.setForeground(new java.awt.Color(255, 0, 0));
        lblErrTtCk.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jblMaHoaDon)
                            .addGap(146, 146, 146)
                            .addComponent(btnTaoHoaDon))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnThanhToan)
                                .addGap(18, 18, 18)
                                .addComponent(btnInHoaDon))
                            .addComponent(jLabel25)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnVoucher)
                                .addGap(18, 18, 18)
                                .addComponent(btnApDung)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyVoucher))
                            .addComponent(jLabel17)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btChonKhachHang)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyKhachHang))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHoanTien))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtChuyenKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel27)))
                            .addComponent(jLabel26)
                            .addComponent(lblErrTtTm, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrTtCk, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jblMaHoaDon)
                    .addComponent(btnTaoHoaDon))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChonKhachHang)
                    .addComponent(btnHuyKhachHang))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoucher)
                    .addComponent(btnApDung)
                    .addComponent(btnHuyVoucher))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbbThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(0, 0, 0)
                .addComponent(lblErrTtTm)
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChuyenKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(0, 0, 0)
                .addComponent(lblErrTtCk)
                .addGap(10, 10, 10)
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(btnHoanTien))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnInHoaDon))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Giày", "Tên Giày", "Giá", "Số Lượng", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(25);
        tblHoaDon.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane5.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jTabbedPane1.addTab("tab1", jScrollPane5);

        jLabel38.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel38.setText("Hóa Đơn Chờ");

        tblHoaDonCho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Tên Khách Hàng", "Thời Gian Tạo", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonCho.setRowHeight(25);
        tblHoaDonCho.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblHoaDonCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonCho);
        if (tblHoaDonCho.getColumnModel().getColumnCount() > 0) {
            tblHoaDonCho.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblHoaDonCho.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblHoaDonCho.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtSearchTenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchTenSanPham.setActionCommand("<Not Set>");
        txtSearchTenSanPham.setMinimumSize(new java.awt.Dimension(64, 30));
        txtSearchTenSanPham.setPreferredSize(new java.awt.Dimension(64, 30));

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(86, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtSearchTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Mục", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        cbbLoaiSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giày Chạy Bộ", "Giày Bóng Rổ", "Giày Đá Banh", "Giày Đi Bộ", "Giày Quần Vợt" }));
        cbbLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbLoaiSanPhamMouseClicked(evt);
            }
        });
        cbbLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cbbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        btnPreSP.setBackground(new java.awt.Color(0, 153, 153));
        btnPreSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPreSP.setForeground(new java.awt.Color(255, 255, 255));
        btnPreSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/View/prev.png"))); // NOI18N
        btnPreSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreSPActionPerformed(evt);
            }
        });

        lblPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPage.setText("1/10");

        btnNextSP.setBackground(new java.awt.Color(0, 153, 153));
        btnNextSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNextSP.setForeground(new java.awt.Color(255, 255, 255));
        btnNextSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/View/next.png"))); // NOI18N
        btnNextSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNextSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTabbedPane1)
                                    .addComponent(jScrollPane2))
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPreSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextSP)
                        .addGap(428, 428, 428))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPreSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnNextSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThanhToanActionPerformed

        this.updateCbbThanhToan();
    }//GEN-LAST:event_cbbThanhToanActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed

        this.thanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed

        this.inHoaDon(jblMaHoaDon.getText(), true);
    }//GEN-LAST:event_btnInHoaDonActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed

        this.createHoaDon();
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed

        this.fillPanelSanPham();
//        thongBao.thongBao("Tìm thấy " + qLy.soLuongSp() + " sản phẩm");
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTienMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMatKeyReleased

        tienMat();
    }//GEN-LAST:event_txtTienMatKeyReleased

    private void txtChuyenKhoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChuyenKhoanKeyReleased

        chuyenKhoan();
    }//GEN-LAST:event_txtChuyenKhoanKeyReleased

    private void btChonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonKhachHangActionPerformed

        this.frameKhachHang("Khách Hàng");
    }//GEN-LAST:event_btChonKhachHangActionPerformed

    private void btnHuyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyKhachHangActionPerformed

        this.huyKhachHang();
    }//GEN-LAST:event_btnHuyKhachHangActionPerformed

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed

        this.frameVoucher("Voucher");
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed

        this.inputThanhTien(true);
    }//GEN-LAST:event_btnApDungActionPerformed

    private void btnHuyVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyVoucherActionPerformed

        this.huyVoucher();
    }//GEN-LAST:event_btnHuyVoucherActionPerformed

    private void btnHoanTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanTienActionPerformed

        if (jblMaHoaDon.getText().equals("#####")) {

            thongBao.thongBao("Chọn hóa đơn cần trả lại tiền dư");
        } else {

            if (txtTienMat.getText().trim().isEmpty() && txtChuyenKhoan.getText().trim().isEmpty()) {

                thongBao.thongBao("Khách hàng chưa thanh toán hóa đơn");
            } else {
                if ((txtTienDu.getText().trim().isEmpty() || Long.parseLong(txtTienDu.getText()) == 0)) {

                    thongBao.thongBao("Khách hàng thanh toán đủ");
                } else if (Long.parseLong(txtTienDu.getText()) < 0) {

                    thongBao.thongBao("Khách hàng thanh toán thiếu");
                } else {

                    String thanhTien = txtThanhTien.getText().replace(".", "");
                    
                    if (!txtTienMat.getText().trim().isEmpty() && !txtChuyenKhoan.getText().trim().isEmpty()) {
                        
                        if (Long.parseLong(txtTienMat.getText()) == Long.parseLong(thanhTien)) {
                            
                            txtChuyenKhoan.setText(null);
                        } else if (Long.parseLong(txtTienMat.getText()) > Long.parseLong(thanhTien)) {
                            
                            txtTienMat.setText(thanhTien);
                            txtChuyenKhoan.setText(null);
                        }  else if (Long.parseLong(txtChuyenKhoan.getText()) > Long.parseLong(thanhTien)) {
                            
                            txtTienMat.setText(null);
                            txtChuyenKhoan.setText(thanhTien);
                        } else if (Long.parseLong(txtChuyenKhoan.getText()) == Long.parseLong(thanhTien)) {
                            
                            txtTienMat.setText(null);
                        } else if (Long.parseLong(txtChuyenKhoan.getText()) == Long.parseLong(txtTienDu.getText())) {
                            
                            txtChuyenKhoan.setText(null);
                        } else if (Long.parseLong(txtChuyenKhoan.getText()) > Long.parseLong(txtTienDu.getText())) {
                            
                            long tienTra = Long.parseLong(txtChuyenKhoan.getText()) - Long.parseLong(txtTienDu.getText());
                            txtChuyenKhoan.setText(String.valueOf(tienTra));
                        } else if (Long.parseLong(txtTienMat.getText()) == Long.parseLong(txtTienDu.getText())) {
                            
                            txtTienMat.setText(null);
                        } else if (Long.parseLong(txtTienMat.getText()) > Long.parseLong(txtTienDu.getText())) {
                            
                            long tienTra = Long.parseLong(txtTienMat.getText()) - Long.parseLong(txtTienDu.getText());
                            txtTienMat.setText(String.valueOf(tienTra));
                        } else {
                            
                            long tienTra = Long.parseLong(txtTienMat.getText()) + Long.parseLong(txtChuyenKhoan.getText()) - Long.parseLong(txtTienDu.getText());
                            txtTienMat.setText(String.valueOf(tienTra));
                        }
                    } else if (!txtTienMat.getText().trim().isEmpty()) {
                        
                        txtTienMat.setText(thanhTien);
                    } else if (!txtChuyenKhoan.getText().trim().isEmpty()) {
                        
                        txtChuyenKhoan.setText(thanhTien);
                    }
                    txtTienDu.setText("0");
                    thongBao.thongBao("Đã trả lại tiền dư cho khách hàng");
                }
            }
        }
    }//GEN-LAST:event_btnHoanTienActionPerformed

    private void cbbLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiSanPhamActionPerformed

        if (cbbLoaiSanPham.getSelectedItem() != null) {
            this.fillPanelSanPham();
        }
    }//GEN-LAST:event_cbbLoaiSanPhamActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.updateSoLuong();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.updateTrangThai();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tblHoaDonChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChoMouseClicked

        this.showData(tblHoaDon.getSelectedRow());
    }//GEN-LAST:event_tblHoaDonChoMouseClicked

    private void cbbThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbThanhToanMouseClicked

    }//GEN-LAST:event_cbbThanhToanMouseClicked

    private void cbbLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLoaiSanPhamMouseClicked

    }//GEN-LAST:event_cbbLoaiSanPhamMouseClicked

    private void txtTienMatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMatKeyPressed

//        this.tienMat();
    }//GEN-LAST:event_txtTienMatKeyPressed

    private void txtTienMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMatKeyTyped

//        this.tienMat();
    }//GEN-LAST:event_txtTienMatKeyTyped

    private void txtChuyenKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChuyenKhoanKeyPressed

//        this.chuyenKhoan();
    }//GEN-LAST:event_txtChuyenKhoanKeyPressed

    private void txtChuyenKhoanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChuyenKhoanKeyTyped

//        this.chuyenKhoan();
    }//GEN-LAST:event_txtChuyenKhoanKeyTyped

    private void btnPreSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreSPActionPerformed
        if (currentPage > 1) {
            currentPage--;
            fillPanelSanPham();
        }
    }//GEN-LAST:event_btnPreSPActionPerformed

    private void btnNextSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSPActionPerformed
        if (currentPage < qLy.getTotalPages(txtSearchTenSanPham.getText(), cbbLoaiSanPham.getSelectedItem().toString())) {
            currentPage++;
            fillPanelSanPham();
        }
    }//GEN-LAST:event_btnNextSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChonKhachHang;
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnHoanTien;
    private javax.swing.JButton btnHuyKhachHang;
    private javax.swing.JButton btnHuyVoucher;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnNextSP;
    private javax.swing.JButton btnPreSP;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnVoucher;
    private javax.swing.JComboBox<String> cbbLoaiSanPham;
    private javax.swing.JComboBox<String> cbbThanhToan;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblMaHoaDon;
    private javax.swing.JLabel lblErrTtCk;
    private javax.swing.JLabel lblErrTtTm;
    private javax.swing.JLabel lblPage;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonCho;
    private javax.swing.JTextField txtChuyenKhoan;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextField txtSearchTenSanPham;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTienDu;
    private javax.swing.JTextField txtTienMat;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    public void fillPanelSanPham() {
        this.removePanel();
        this.qLy.getAllSanPham(txtSearchTenSanPham.getText(), cbbLoaiSanPham.getSelectedItem().toString(),
                jblMaHoaDon, jPanel1, tblHoaDon, tblHoaDonCho, txtTongTien, txtThanhTien,
                        jTabbedPane1, idNhanVien, currentPage, txtTenKhachHang);
        this.lblPage.setText(currentPage + "/" + qLy.getTotalPages(txtSearchTenSanPham.getText().trim(), cbbLoaiSanPham.getSelectedItem().toString()));
    }

    public void frameKhachHang(String title) {
        
        if (jblMaHoaDon.getText().equals("#####")) {

            DiaLogYesNo logYesNo = new DiaLogYesNo(null, "Tạo hóa đơn mới cho khách hàng?");
            logYesNo.setVisible(true);

            if (logYesNo.getResult() == JOptionPane.YES_OPTION) {
                String ma = qLy.createMaHoaDon();
                qLy.themHoaDonMoi(idNhanVien);
                qLy.fillTableHoaDonCho(tblHoaDonCho);
                jTabbedPane1.setTitleAt(0, ma);
                jblMaHoaDon.setText(ma);
                tblHoaDonCho.setRowSelectionInterval(tblHoaDonCho.getRowCount() - 1, tblHoaDonCho.getRowCount() - 1);

                createFromKhachHang();
            }
        } else {
            createFromKhachHang();
        }
    }

    public void frameVoucher(String title) {

        if (jblMaHoaDon.getText().equals("#####")) {

            DiaLogYesNo logYesNo = new DiaLogYesNo(null, "Tạo hóa đơn mới cho voucher bạn muốn chọn?");
            logYesNo.setVisible(true);

            if (logYesNo.getResult() == JOptionPane.YES_OPTION) {
                String ma = qLy.createMaHoaDon();
                qLy.themHoaDonMoi(idNhanVien);
                qLy.fillTableHoaDonCho(tblHoaDonCho);
                jTabbedPane1.setTitleAt(0, ma);
                jblMaHoaDon.setText(ma);
                tblHoaDonCho.setRowSelectionInterval(tblHoaDonCho.getRowCount() - 1, tblHoaDonCho.getRowCount() - 1);

                createFromVoucher();
            }
        } else {
            createFromVoucher();
        }
    }

    public void updateCbbThanhToan() {

        if (tblHoaDonCho.getSelectedRow() != -1) {

            switch (cbbThanhToan.getSelectedIndex()) {
                case 0 -> {
                    txtChuyenKhoan.setEnabled(false);
                    txtTienMat.setEnabled(true);
                    txtChuyenKhoan.setText(null);
                    txtTienDu.setText(null);
                }
                case 1 -> {
                    txtChuyenKhoan.setEnabled(true);
                    txtTienMat.setEnabled(false);
                    txtTienMat.setText(null);
                    txtTienDu.setText(null);
                }
                default -> {
                    txtChuyenKhoan.setEnabled(true);
                    txtTienMat.setEnabled(true);
                }
            }
        }
    }

    public void createHoaDon() {
        DefaultTableModel tblModel = (DefaultTableModel) tblHoaDonCho.getModel();
        tblModel.setRowCount(0);

        jTabbedPane1.setTitleAt(0, qLy.createMaHoaDon());
        jblMaHoaDon.setText(qLy.createMaHoaDon());
        DefaultTableModel tblModelHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        tblModelHoaDon.setRowCount(0);
        qLy.themHoaDonMoi(idNhanVien);
        this.qLy.fillTableHoaDonCho(tblHoaDonCho);
        cleanTextKhachHang();
        cleanTextVoucher();
        tblHoaDonCho.setRowSelectionInterval(tblHoaDonCho.getRowCount() - 1, tblHoaDonCho.getRowCount() - 1);

        txtTenKhachHang.setText("Khách Vãng Lai");
        thongBao.thongBao("Tạo hóa đơn thành công");
    }

    public void showData(int index) {

        String ma = qLy.getHoaDon(tblHoaDonCho.getSelectedRow()).getMaHoaDon();
        int indexHdC = tblHoaDonCho.getSelectedRow();

        jTabbedPane1.setTitleAt(0, ma);
        jblMaHoaDon.setText(ma);
        qLy.fillTableHoaDon(tblHoaDon, tblHoaDonCho, ma);
        qLy.tongTien(txtTongTien, txtThanhTien);

        String tenKH = qLy.getAllHoaDonCho().get(indexHdC).getTenKhachHang();

        txtTenKhachHang.setText(tenKH);
        txtSoDienThoai.setText(qLy.getAllHoaDonCho().get(indexHdC).getSoDienThoai());

        if (tenKH.equals("Khách Vãng Lai")) {
            txtSoDienThoai.setText(null);
        }

        VoucherModel voucherModel = voucherRepo.getIdVoucher(qLy.getAllHoaDonCho().get(indexHdC).getIdVoucher());
        if (voucherModel.getMaVoucher() != null) {

            txtMaVoucher.setText(voucherModel.getMaVoucher());
            if (voucherModel.getLoaiVoucher().contains("%")) {

                txtGiamGia.setText(voucherModel.getGiaTri() + " %");
            } else {
                txtGiamGia.setText(voucherModel.getGiaTri() + " VNĐ");
            }
        } else {
            txtMaVoucher.setText(null);
            txtGiamGia.setText(null);
        }
        txtTienMat.setText(null);
        txtChuyenKhoan.setText(null);
        txtTienDu.setText(null);

        this.fillPanelSanPham();
    }

    public void inputThanhTien(boolean tb) {
        if (txtTongTien.getText().isEmpty()) {

            thongBao.thongBao("Chọn hóa đơn cần áp Voucher");
        } else if (txtMaVoucher.getText().isEmpty()) {

            thongBao.thongBao("Chưa chọn mã Voucher nào!");
        } else {
            String tongTien = txtTongTien.getText().replace(".", "");
            int spaceIndex = txtGiamGia.getText().indexOf(" ");

            long tong = Long.parseLong(tongTien);
            int giam = Integer.parseInt(txtGiamGia.getText().substring(0, spaceIndex));

            long thanhTien;
            if (txtGiamGia.getText().contains("%")) {

                thanhTien = tong - ((tong / 100) * giam);
            } else {

                thanhTien = Integer.parseInt(tongTien) - Integer.parseInt(txtGiamGia.getText().substring(0, spaceIndex));
            }
            DecimalFormat format = new DecimalFormat("#,###");
            String numberFormat = format.format(thanhTien);

            txtThanhTien.setText(numberFormat);
            txtTienMat.setText(null);
            txtChuyenKhoan.setText(null);
            if (tb) {

                thongBao.thongBao("Đã áp dụng Voucher thành công");
            }
        }
    }

    public void inputThanhToan(JTextField txtTtLoai1, JTextField txtTtLoai2) {

        lblErrTtTm.setText(" ");
        lblErrTtCk.setText(" ");

        String thanhTien = txtThanhTien.getText().replace(".", "");

        long tienDu = 0;

        if (txtTtLoai2.getText().length() > 13) {

            thongBao.thongBao("Vui lòng nhập dưới 999 tỷ");
        } else {
            if (txtTtLoai2.getText().isEmpty()) {

            } else if (txtTtLoai1.getText().isEmpty()) {

                tienDu = Long.parseLong(txtTtLoai2.getText()) - Integer.parseInt(thanhTien);
            } else {

                tienDu = Long.parseLong(txtTtLoai1.getText()) + Integer.parseInt(txtTtLoai2.getText()) - Integer.parseInt(thanhTien);
            }

            txtTienDu.setText(String.valueOf(tienDu));
        }
    }

    public void modelComboBox() {
        DefaultComboBoxModel comboBox = (DefaultComboBoxModel) cbbLoaiSanPham.getModel();
        comboBox.removeAllElements();

        comboBox.addElement("Tất Cả");

        for (String x : qLy.modelComboBox()) {
            comboBox.addElement(x);
        }
    }

    public void thanhToan() {

        if (jblMaHoaDon.getText().equals("#####")) {

            thongBao.thongBao("Chọn hóa đơn cần thanh toán");

        } else if (checkTable()) {
            long tienDu;
            long tienMat;
            long tienCk;

            try {
                tienDu = Long.parseLong(txtTienDu.getText());
            } catch (NumberFormatException e) {
                tienDu = -1;
            }

            try {
                tienMat = Long.parseLong(txtTienMat.getText());
            } catch (NumberFormatException e) {
                tienMat = -1;
            }

            try {
                tienCk = Long.parseLong(txtChuyenKhoan.getText());
            } catch (NumberFormatException e) {
                tienCk = -1;
            }
            if (tienMat <= 0 && tienCk <= 0) {

                thongBao.thongBao("Khách hàng chưa thanh toán hóa đơn");

            } else if (tienDu < 0) {

                thongBao.thongBao("Khách hàng thanh toán còn thiếu");
            } else if (tienDu > 1000000) {

                thongBao.thongBao("Trả lại tiền thừa cho khách hàng");
            } else {

                if (checkVoucher()) {
                    String thanhTien = txtThanhTien.getText().replace(".", "");
                    long tongTien = Long.parseLong(thanhTien);
                    String loai = cbbThanhToan.getSelectedItem().toString();

                    if (cbbThanhToan.getSelectedIndex() == 2) {

                        if (tienMat <= 0 || txtTienMat.getText().trim().isEmpty()) {

                            loai = "Chuyển Khoản";
                        }
                        if (tienCk <= 0 || txtChuyenKhoan.getText().trim().isEmpty()) {

                            loai = "Tiền Mặt";
                        }
                    }
                    this.qLy.updateThanhToanHoaDon(loai, tongTien,
                            qLy.getHoaDon(tblHoaDonCho.getSelectedRow()).getId());

                    thongBao.thongBao("Thanh toán thành công");
                    inHoaDon("HoaDon\\" + jblMaHoaDon.getText(), false);
                    this.loadForm();
                }
            }
        }
    }

    public void huyKhachHang() {

        int indexHdC = tblHoaDonCho.getSelectedRow();

        if (indexHdC != -1) {
            if (txtTenKhachHang.getText().equals("Khách Vãng Lai")) {

                thongBao.thongBao("Hóa đơn này đang là của khách vãng lai");
            } else {
                this.qLy.suaKhachHangHoaDon(qLy.getHoaDon(tblHoaDonCho.getSelectedRow()).getId());
                this.qLy.fillTableHoaDonCho(tblHoaDonCho);
                tblHoaDonCho.setRowSelectionInterval(indexHdC, indexHdC);
                thongBao.thongBao("Đã đổi hóa đơn " + jblMaHoaDon.getText() + " thành của khách vãng lai");

                txtTenKhachHang.setText("Khách Vãng Lai");
                txtSoDienThoai.setText(null);
            }

        } else {

            thongBao.thongBao("Chọn hóa đơn của khách hàng cần hủy");
        }
    }

    public void huyVoucher() {
        if (tblHoaDonCho.getSelectedRow() != -1) {

            if (!txtMaVoucher.getText().isEmpty()) {

                this.qLy.suaVoucherHoaDon(qLy.getHoaDon(tblHoaDonCho.getSelectedRow()).getId());
                txtMaVoucher.setText(null);
                txtGiamGia.setText(null);
                txtThanhTien.setText(txtTongTien.getText());

                thongBao.thongBao("Hủy Voucher thành công");
            } else {   

                thongBao.thongBao("Hóa đơn chưa được áp Voucher");
            }

        } else {

            thongBao.thongBao("Chọn hóa đơn muốn hủy Voucher");
        }
    }

    public void setMouse() {
        txtSearchTenSanPham.requestFocus();
    }

    public void createFromKhachHang() {

        int index = tblHoaDonCho.getSelectedRow();
        JFrame frame = new JFrame(title);
        frame.setSize(617, 540);
        frame.setLocationRelativeTo(null);

        KhachHangPanel kh = new KhachHangPanel(frame, txtTenKhachHang, txtSoDienThoai, index,
                qLy.getAllHoaDonCho().get(tblHoaDonCho.getSelectedRow()).getId(), tblHoaDonCho);
        frame.add(kh);
        frame.setVisible(true);
    }

    public void createFromVoucher() {

        int loadTable = 1;
        JFrame frame = new JFrame(title);
        frame.setSize(617, 600);
        frame.setLocationRelativeTo(null);

        VoucherPanel voucher = new VoucherPanel(frame, txtMaVoucher, txtGiamGia,
                qLy.getAllHoaDonCho().get(tblHoaDonCho.getSelectedRow()).getId(), loadTable);

        frame.add(voucher);
        frame.setVisible(true);
    }

    public void removeTitleBar() {
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    public void updateSoLuong() {

        int soLuong;

        DiaLogYesNo logYesNo = new DiaLogYesNo(null, "Bạn có muốn sửa số lượng sản phẩm này ?");
        logYesNo.setVisible(true);

        int indexHdC = tblHoaDonCho.getSelectedRow();
        int indexHd = tblHoaDon.getSelectedRow();

        if (logYesNo.getResult() == JOptionPane.YES_OPTION) {

            try {

                DiaLogInput input = new DiaLogInput(null);
                input.setVisible(true);
                soLuong = input.getInputValue();

            } catch (NumberFormatException e) {
                soLuong = 0;
            }

            if (soLuong > 0) {

                int soLuongCu = Integer.parseInt(tblHoaDon.getValueAt(indexHd, 3).toString());

                if (soLuong <= qLy.getIdMaSpct(tblHoaDon.getValueAt(indexHd, 0).toString()).getSoLuong() + soLuongCu) {

                    if (soLuong != Integer.parseInt(tblHoaDon.getValueAt(indexHd, 3).toString())) {

                        qLy.updateSoLuong(soLuongCu, soLuong, qLy.getIdMaSpct(tblHoaDon.getValueAt(indexHd, 0).toString()).getId());
                    }
                    qLy.updateSoLuongHdct(soLuong, qLy.getAllHoaDon(qLy.getHoaDon(indexHdC)
                            .getMaHoaDon()).get(tblHoaDon.getSelectedRow()).getId());
                } else {

                    thongBao.thongBao("Số lượng sản phẩm không đủ");
                }
            } else {
                
                thongBao.thongBao("Số lượng sản phẩm phải > 0");
            }
        }
        fillPanelSanPham();
        qLy.fillTableHoaDon(tblHoaDon, tblHoaDonCho, jblMaHoaDon.getText());
        qLy.tongTien(txtTongTien, txtThanhTien);
        tblHoaDonCho.setRowSelectionInterval(indexHdC, indexHdC);
    }

    public void updateTrangThai() {

        DiaLogYesNo logYesNo = new DiaLogYesNo(null, "Bạn có muốn hủy chọn sản phẩm này?");
        logYesNo.setVisible(true);

        if (logYesNo.getResult() == JOptionPane.YES_OPTION) {

            qLy.getSoLuongSpct(Integer.parseInt(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 3).toString()),
                    qLy.getIdMaSpct(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0).toString()).getId());

            qLy.updateTrangThaiHdct(qLy.getAllHoaDon(qLy.getHoaDon(tblHoaDonCho.getSelectedRow())
                    .getMaHoaDon()).get(tblHoaDon.getSelectedRow()).getId());

            fillPanelSanPham();
            qLy.fillTableHoaDon(tblHoaDon, tblHoaDonCho, jblMaHoaDon.getText());
            qLy.tongTien(txtTongTien, txtThanhTien);
        }
    }

    public void hovers() {
        hover(txtTenKhachHang);
        hover(txtSoDienThoai);
        hover(txtTongTien);
        hover(txtMaVoucher);
        hover(txtGiamGia);
        hover(txtThanhTien);
        hover(txtTienDu);
    }

    public void hover(JTextField txtInput) {

        txtInput.addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {
                e.consume();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                e.consume();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                e.consume();
            }
        });
    }

    public void showPopup(JTable table) {
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                showPopup(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                showPopup(e);
            }

            private void showPopup(MouseEvent e) {
                if (e.isPopupTrigger()) {

                    int row = table.rowAtPoint(e.getPoint());
                    int column = table.columnAtPoint(e.getPoint());

                    if (row >= 0 && column >= 0) {

                        table.setRowSelectionInterval(row, row);
                        table.setColumnSelectionInterval(column, column);

                        jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
                    }
                }
            }
        });
    }

    public boolean checkTable() {
        if (tblHoaDon.getRowCount() == 0) {

            thongBao.thongBao("Hóa đơn trống");
            return false;
        }
        return true;
    }

    public void loadForm() {
        jblMaHoaDon.setText("#####");
        cleanTextKhachHang();
        txtTongTien.setText(null);
        cleanTextVoucher();
        txtThanhTien.setText(null);
        cbbThanhToan.setSelectedIndex(0);
        txtTienMat.setText(null);
        txtChuyenKhoan.setText(null);
        txtTienDu.setText(null);
        cleanTable();
        qLy.fillTableHoaDonCho(tblHoaDonCho);
        txtSearchTenSanPham.setText(null);
        cbbLoaiSanPham.setSelectedIndex(0);
        fillPanelSanPham();
    }

    public void cleanTable() {
        jTabbedPane1.setTitleAt(0, "Mã Hóa Đơn");
        DefaultTableModel tblModel = (DefaultTableModel) tblHoaDon.getModel();
        tblModel.setRowCount(0);
    }

    public void cleanTextKhachHang() {
        txtTenKhachHang.setText(null);
        txtSoDienThoai.setText(null);
    }

    public void cleanTextVoucher() {
        txtMaVoucher.setText(null);
        txtGiamGia.setText(null);
    }

    public void cleanTien() {
        txtTongTien.setText("0");
        txtThanhTien.setText("0");
    }

    public void removePanel() {
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void inHoaDon(String ma, boolean in) {

        if (jblMaHoaDon.getText().equals("#####")) {

            thongBao.thongBao("Chọn hóa đơn cần in");
        } else if (txtTongTien.getText().length() < 2) {

            thongBao.thongBao("Hóa đơn trống");
        } else {
            if (!txtMaVoucher.getText().isEmpty()) {

                this.inputThanhTien(false);
            }
            qLy.xuatHoaDon(ma, txtTenKhachHang.getText(), txtSoDienThoai.getText(), txtTongTien.getText(),
                    txtMaVoucher.getText(), txtGiamGia.getText(), txtThanhTien.getText(), in);

        }
    }

    public void tienMat() {
        String thanhTien = txtThanhTien.getText().replace(".", "");
        
        if (jblMaHoaDon.getText().equals("#####")) {
            
            thongBao.thongBao("Chọn hóa đơn để thanh toán");
        } else if (txtThanhTien.getText().isEmpty() || Integer.parseInt(thanhTien) == 0) {
            
            thongBao.thongBao("Hóa đơn trống");
        } else {
            
            Pattern pattern = Pattern.compile("\\d+");
            Matcher matcher = pattern.matcher(txtTienMat.getText());

            if (!matcher.matches()) {

                thongBao.thongBao("Vui lòng thanh toán đúng giá trị");
            } else {
                this.inputThanhToan(txtChuyenKhoan, txtTienMat);
            }
        }
    }

    public void chuyenKhoan() {

        String thanhTien = txtThanhTien.getText().replace(".", "");
        
        if (jblMaHoaDon.getText().equals("#####")) {
            
            thongBao.thongBao("Chọn hóa đơn để thanh toán");
        } else if (txtThanhTien.getText().isEmpty() || Integer.parseInt(thanhTien) == 0) {
            
            thongBao.thongBao("Hóa đơn trống");
        } else {
            
            Pattern pattern = Pattern.compile("\\d+");
            Matcher matcher = pattern.matcher(txtChuyenKhoan.getText());

            if (!matcher.matches()) {

                thongBao.thongBao("Vui lòng thanh toán đúng giá trị");
            } else {
                this.inputThanhToan(txtTienMat, txtChuyenKhoan);
            }
        }
    }

    public boolean checkVoucher() {

        if (txtThanhTien.getText().equals(txtTongTien.getText())) {

            this.huyVoucher();
            return true;
        }
        return true;
    }
}
