/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Internal;

import Model.Internal.DanhMucModel;
import Model.Internal.ThongKeModel;
import Repository.Internal.ThongKeRepo;
import Service.DanhMucService;
import View.Dialog.DiaLogThongBao;
import View.Panel.DanhMucPanel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lcinu
 */
public class ThongKeInternal extends javax.swing.JInternalFrame {

    ThongKeRepo repoTK = new ThongKeRepo();

    SanPhamInternal sp = new SanPhamInternal();
    private final DanhMucService danhMucService = new DanhMucService();
    private DanhMucPanel dm = new DanhMucPanel();
    private DiaLogThongBao  thongBao = new DiaLogThongBao();

    /**
     * Creates new form HomeInternal
     */
    public ThongKeInternal() {
        initComponents();

        this.removeTitleBar();
        this.fillTableThongKeSP();

        this.fillDoanhThuHomNay();
        this.fillDoanhThu7ngay();
        this.fillDoanhThu1Thang();
        this.loadCOomBoBox(this.danhMucService.getAllDanhMucByTrangThai(0), cbbSearchDanhMuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        XuatExcel = new javax.swing.JButton();
        txtXuatNgatBD = new com.toedter.calendar.JDateChooser();
        txtXuatNgatKT = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblslhdHomNay = new javax.swing.JLabel();
        lblDoanhThuHomNay = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblslhd7ngay = new javax.swing.JLabel();
        lblDoanhThu7ngay = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblslhdTuyChon = new javax.swing.JLabel();
        lblDoanhThuTuyChon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblslhdThangNay = new javax.swing.JLabel();
        lblDoanhThuThangNay = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnDoanhThuTuyChon = new javax.swing.JButton();
        txtTuyChonNgayBD = new com.toedter.calendar.JDateChooser();
        txtTuyChonNgayKT = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeSP = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbbSearchDanhMuc = new javax.swing.JComboBox<>();
        Loc = new javax.swing.JButton();
        txtLocNgayBD = new com.toedter.calendar.JDateChooser();
        txtLocNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setBorder(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1246, 864));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thống Kê Doanh Thu");

        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Từ:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Đến:");

        XuatExcel.setBackground(new java.awt.Color(0, 153, 153));
        XuatExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XuatExcel.setForeground(new java.awt.Color(255, 255, 255));
        XuatExcel.setText("Xuất");
        XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatExcelActionPerformed(evt);
            }
        });

        txtXuatNgatBD.setDateFormatString("dd-MM-yyyy");
        txtXuatNgatBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtXuatNgatKT.setDateFormatString("dd-MM-yyyy");
        txtXuatNgatKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtXuatNgatBD, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(txtXuatNgatKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(XuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtXuatNgatBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(txtXuatNgatKT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hôm Nay");

        lblslhdHomNay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblslhdHomNay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblslhdHomNay.setText("Hóa Đơn Bán: X");
        lblslhdHomNay.setToolTipText("");
        lblslhdHomNay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblslhdHomNay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDoanhThuHomNay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhThuHomNay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuHomNay.setText("X VNĐ");
        lblDoanhThuHomNay.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblslhdHomNay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoanhThuHomNay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(lblDoanhThuHomNay)
                .addGap(25, 25, 25)
                .addComponent(lblslhdHomNay)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7 Ngày");

        lblslhd7ngay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblslhd7ngay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblslhd7ngay.setText("Hóa Đơn Bán: X");
        lblslhd7ngay.setToolTipText("");
        lblslhd7ngay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblslhd7ngay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDoanhThu7ngay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhThu7ngay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThu7ngay.setText("X VNĐ");
        lblDoanhThu7ngay.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblslhd7ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoanhThu7ngay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(25, 25, 25)
                .addComponent(lblDoanhThu7ngay)
                .addGap(25, 25, 25)
                .addComponent(lblslhd7ngay)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tùy Chọn");

        lblslhdTuyChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblslhdTuyChon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblslhdTuyChon.setText("Hóa Đơn Bán: X");
        lblslhdTuyChon.setToolTipText("");
        lblslhdTuyChon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblslhdTuyChon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDoanhThuTuyChon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhThuTuyChon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuTuyChon.setText("X VNĐ");
        lblDoanhThuTuyChon.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblslhdTuyChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoanhThuTuyChon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(25, 25, 25)
                .addComponent(lblDoanhThuTuyChon)
                .addGap(25, 25, 25)
                .addComponent(lblslhdTuyChon)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tháng");

        lblslhdThangNay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblslhdThangNay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblslhdThangNay.setText("Hóa Đơn Bán: X");
        lblslhdThangNay.setToolTipText("");
        lblslhdThangNay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblslhdThangNay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDoanhThuThangNay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhThuThangNay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuThangNay.setText("X VNĐ");
        lblDoanhThuThangNay.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblslhdThangNay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoanhThuThangNay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel19)
                .addGap(25, 25, 25)
                .addComponent(lblDoanhThuThangNay)
                .addGap(25, 25, 25)
                .addComponent(lblslhdThangNay)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Từ:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Đến:");

        btnDoanhThuTuyChon.setBackground(new java.awt.Color(0, 153, 153));
        btnDoanhThuTuyChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoanhThuTuyChon.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThuTuyChon.setText("Chọn");
        btnDoanhThuTuyChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuTuyChonActionPerformed(evt);
            }
        });

        txtTuyChonNgayBD.setDateFormatString("yyyy-MM-dd");
        txtTuyChonNgayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTuyChonNgayKT.setDateFormatString("yyyy-MM-dd");
        txtTuyChonNgayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTuyChonNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(txtTuyChonNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoanhThuTuyChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDoanhThuTuyChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuyChonNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(txtTuyChonNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Thống Kê Sản Phẩm");

        tblThongKeSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Giày", "Tên Giày", "Giá Sản Phẩm", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongKeSP.setName(""); // NOI18N
        tblThongKeSP.setRowHeight(25);
        tblThongKeSP.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblThongKeSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongKeSP);
        if (tblThongKeSP.getColumnModel().getColumnCount() > 0) {
            tblThongKeSP.getColumnModel().getColumn(1).setPreferredWidth(120);
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Từ Ngày:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Đến Ngày:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Danh Mục");

        cbbSearchDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbSearchDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả" }));
        cbbSearchDanhMuc.setPreferredSize(new java.awt.Dimension(30, 30));
        cbbSearchDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchDanhMucActionPerformed(evt);
            }
        });

        Loc.setBackground(new java.awt.Color(0, 153, 153));
        Loc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loc.setForeground(new java.awt.Color(255, 255, 255));
        Loc.setText("Lọc");
        Loc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocMouseClicked(evt);
            }
        });
        Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocActionPerformed(evt);
            }
        });

        txtLocNgayBD.setToolTipText("");
        txtLocNgayBD.setDateFormatString("yyyy-MM-dd");
        txtLocNgayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLocNgayBD.setPreferredSize(new java.awt.Dimension(30, 30));

        txtLocNgayKT.setToolTipText("");
        txtLocNgayKT.setDateFormatString("yyyy-MM-dd");
        txtLocNgayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLocNgayKT.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Tên Giày");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLocNgayBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(cbbSearchDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, 0, 249, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txtLocNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtSearch))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLocNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(3, 3, 3)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSearchDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongKeSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThongKeSPMouseClicked

    private void LocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocMouseClicked

    }//GEN-LAST:event_LocMouseClicked

    private void btnDoanhThuTuyChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuTuyChonActionPerformed
        if (checkDateTuyChon()) {
            this.fillDoanhThuTuyChon();
        }
    }//GEN-LAST:event_btnDoanhThuTuyChonActionPerformed

    private void cbbSearchDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSearchDanhMucActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseClicked

    private void XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatExcelActionPerformed
        if (checkDateInHoaDon()) {
            String nbd;
            String nkt;
            if (txtXuatNgatBD.getDate() == null && txtXuatNgatKT.getDate() == null) {

                nbd = "abc";
                nkt = "abc";
            } else {
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                nbd = format.format(txtXuatNgatBD.getDate());
                nkt = format.format(txtXuatNgatKT.getDate());
            }
            repoTK.inThongKeSP(nbd, nkt);
        }
    }//GEN-LAST:event_XuatExcelActionPerformed

    private void LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocActionPerformed
        if (checkDateTable()) {
            fillTableThongKeSP();
        }
    }//GEN-LAST:event_LocActionPerformed
    private void fillTableThongKeSP() {
        DefaultTableModel dblModel = (DefaultTableModel) tblThongKeSP.getModel();
        dblModel.setRowCount(0);
        String nbd ;
        String nkt ;
        if (txtLocNgayBD.getDate() == null && txtLocNgayKT.getDate() == null) {

            nbd = "abc";
            nkt = "abc";
        } else {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            nbd = format.format(txtLocNgayBD.getDate());
            nkt = format.format(txtLocNgayKT.getDate());
        }

        if (cbbSearchDanhMuc.getSelectedItem() != null) {
                for (ThongKeModel x : repoTK.getThongkeSP(txtSearch.getText(), cbbSearchDanhMuc.getSelectedItem().toString(), nbd, nkt)) {
                    dblModel.addRow(x.toDataRowThongKe());
                }
        }
    }

    public void fillDoanhThuHomNay() {
        lblDoanhThuHomNay.setText(String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(0)).get(1)) + " VNĐ");
        lblslhdHomNay.setText("Số hóa đơn bán được: " + String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(0)).get(0)));
    }

    public void fillDoanhThu7ngay() {
        lblDoanhThu7ngay.setText(String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(1)).get(1)) + " VNĐ");
        lblslhd7ngay.setText("Số hóa đơn bán được: " + String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(1)).get(0)));
    }

    public void fillDoanhThu1Thang() {
        lblDoanhThuThangNay.setText(String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(2)).get(1)) + " VNĐ");
        lblslhdThangNay.setText("Số hóa đơn bán được: " + String.valueOf(repoTK.getThongkeSP(repoTK.getThongkeSQL().get(2)).get(0)));
    }

    public void fillDoanhThuTuyChon() {
            String nbd;
            String nkt;
            if (txtTuyChonNgayBD.getDate() == null && txtTuyChonNgayKT.getDate() == null) {
                nbd = "abc";
                nkt = "abc";
            } else {
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                nbd = format.format(txtTuyChonNgayBD.getDate());
                nkt = format.format(txtTuyChonNgayKT.getDate());
            }
            ArrayList<ThongKeModel> thongKeList = repoTK.getThongkeTuyChon(nbd, nkt);
            if (thongKeList != null && !thongKeList.isEmpty()) {
                ThongKeModel thongKe = thongKeList.get(0); // Giả sử bạn chỉ cần lấy kết quả đầu tiên
                lblDoanhThuTuyChon.setText(String.valueOf(thongKe.getTongTien()) + " VNĐ");
                lblslhdTuyChon.setText(String.valueOf("Số hóa đơn bán được: " + thongKe.getSoHoaDon()));
            } else {
                lblDoanhThuTuyChon.setText("0");
                lblslhdTuyChon.setText("0");
            }
    }

    public boolean checkDateTable() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Date nbd = format.parse("2024-01-01");
            if (txtLocNgayBD.getDate() == null && txtLocNgayKT.getDate() == null) {

                return true;
            }
            else if (txtLocNgayBD.getDate() == null && txtLocNgayKT.getDate() != null) {

                thongBao.thongBao("Ngày bắt đầu không được để trống.");
                return false;
            }
            else if (txtLocNgayBD.getDate().before(nbd)) {
                thongBao.thongBao("Ngày bắt đầu phải sau 2024-01-01.");
                return false;
            }
            else if (txtLocNgayBD.getDate() != null && txtLocNgayKT.getDate() == null) {

                thongBao.thongBao("Ngày kết thúc không được để trống.");
                return false;
            }
            else if (txtLocNgayBD.getDate().after(txtLocNgayKT.getDate())) {

                thongBao.thongBao("Ngày bắt đầu không thể sau ngày kết thúc.");
                return false;
            } 
        } catch (Exception e) {
        }

        return true;
    }    
    public boolean checkDateTuyChon() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Date nbd = format.parse("2024-01-01");

            if (txtTuyChonNgayBD.getDate() == null) {
                thongBao.thongBao("Ngày bắt đầu không được để trống.");
                return false;
            } else if (txtTuyChonNgayBD.getDate().before(nbd)) {
                thongBao.thongBao("Ngày bắt đầu phải sau 2024-01-01.");
                return false;
            } else if (txtTuyChonNgayKT.getDate() == null) {
                thongBao.thongBao("Ngày kết thúc không được để trống.");
                return false;
            } else if (txtTuyChonNgayBD.getDate().after(txtTuyChonNgayKT.getDate())) {
                thongBao.thongBao("Ngày bắt đầu không được sau ngày kết thúc.");
                return false;
            }
        } catch (Exception e) {
        }
        return true;
    }

    public boolean checkDateInHoaDon() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Date nbd = format.parse("2024-01-01");
            if (txtXuatNgatBD.getDate() == null) {
                thongBao.thongBao("Ngày bắt đầu không được để trống.");
                return false;
            }
            else if (txtXuatNgatBD.getDate().before(nbd)) {
                thongBao.thongBao("Ngày bắt đầu phải sau 2024-01-01.");
                return false;
            }
            else if (txtXuatNgatKT.getDate() == null) {
                thongBao.thongBao("Ngày kết thúc không được để trống.");
                return false;
            }    
            else if (txtXuatNgatBD.getDate().after(txtXuatNgatKT.getDate())) {
                thongBao.thongBao("Ngày bắt đầu không thể sau ngày kết thúc.");
                return false;
            }
        } catch (Exception e) {
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loc;
    private javax.swing.JButton XuatExcel;
    private javax.swing.JButton btnDoanhThuTuyChon;
    private javax.swing.JComboBox<String> cbbSearchDanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoanhThu7ngay;
    private javax.swing.JLabel lblDoanhThuHomNay;
    private javax.swing.JLabel lblDoanhThuThangNay;
    private javax.swing.JLabel lblDoanhThuTuyChon;
    private javax.swing.JLabel lblslhd7ngay;
    private javax.swing.JLabel lblslhdHomNay;
    private javax.swing.JLabel lblslhdThangNay;
    private javax.swing.JLabel lblslhdTuyChon;
    private javax.swing.JTable tblThongKeSP;
    private com.toedter.calendar.JDateChooser txtLocNgayBD;
    private com.toedter.calendar.JDateChooser txtLocNgayKT;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtTuyChonNgayBD;
    private com.toedter.calendar.JDateChooser txtTuyChonNgayKT;
    private com.toedter.calendar.JDateChooser txtXuatNgatBD;
    private com.toedter.calendar.JDateChooser txtXuatNgatKT;
    // End of variables declaration//GEN-END:variables

    public void removeTitleBar() {
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    private void loadCOomBoBox(List<DanhMucModel> list, JComboBox combo) {

        list.forEach(item -> combo.addItem(item));

    }
    
    public void loadForm() {
        txtLocNgayBD.setDate(null);
        txtLocNgayKT.setDate(null);
        txtTuyChonNgayBD.setDate(null);
        txtTuyChonNgayKT.setDate(null);
        txtXuatNgatBD.setDate(null);
        txtXuatNgatKT.setDate(null);
        txtSearch.setText(null);
        cbbSearchDanhMuc.setSelectedIndex(0);
        this.fillDoanhThuHomNay();
        this.fillDoanhThu7ngay();
        this.fillDoanhThu1Thang();
        this.fillTableThongKeSP();
    }
}
