/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View.Login;

import Repository.Main.Repo_Admin;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author lcinu
 */
public class ShoeStoreView extends javax.swing.JFrame {
    
    private Repo_Admin connext = new Repo_Admin();
    private final int idNhanVien;
    

    /** Creates new form ShoeStoreView
     * @param idNhanVien */
    public ShoeStoreView(int idNhanVien) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.hoverPanelMenu();
        connext.home(dtpModel);
        this.idNhanVien = idNhanVien;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBanHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnVoucher = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dtpModel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlMenu.setBackground(new java.awt.Color(0, 153, 153));
        pnlMenu.setLayout(new java.awt.GridLayout(12, 1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel2);

        btnBanHang.setBackground(new java.awt.Color(0, 204, 204));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Sell.png"))); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.setIconTextGap(23);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBanHang);

        btnHoaDon.setBackground(new java.awt.Color(0, 204, 204));
        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Receipt.png"))); // NOI18N
        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.setIconTextGap(23);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        pnlMenu.add(btnHoaDon);

        btnSanPham.setBackground(new java.awt.Color(0, 204, 204));
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Shoe.png"))); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanPham.setIconTextGap(23);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSanPham);

        btnVoucher.setBackground(new java.awt.Color(0, 204, 204));
        btnVoucher.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Sale.png"))); // NOI18N
        btnVoucher.setText("Voucher");
        btnVoucher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVoucher.setIconTextGap(23);
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });
        pnlMenu.add(btnVoucher);

        btnThongKe.setBackground(new java.awt.Color(0, 204, 204));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Analytics.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.setIconTextGap(23);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pnlMenu.add(btnThongKe);

        btnKhachHang.setBackground(new java.awt.Color(0, 204, 204));
        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Clien.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setIconTextGap(23);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        pnlMenu.add(btnKhachHang);

        btnNhanVien.setBackground(new java.awt.Color(0, 204, 204));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Management.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setIconTextGap(23);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        pnlMenu.add(btnNhanVien);

        btnDangXuat.setBackground(new java.awt.Color(0, 204, 204));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu/Door.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuat.setIconTextGap(23);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDangXuat);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel4);

        javax.swing.GroupLayout dtpModelLayout = new javax.swing.GroupLayout(dtpModel);
        dtpModel.setLayout(dtpModelLayout);
        dtpModelLayout.setHorizontalGroup(
            dtpModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        dtpModelLayout.setVerticalGroup(
            dtpModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dtpModel)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dtpModel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        
        connext.banHang(dtpModel, idNhanVien);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        
        connext.hoaDon(dtpModel);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        
        connext.sanPham(dtpModel);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        
        connext.voucher(dtpModel);
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        
        connext.thongKe(dtpModel);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        
        connext.khachHang(dtpModel);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        
        connext.nhanVien(dtpModel);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnVoucher;
    private javax.swing.JDesktopPane dtpModel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

  
    public void OpenMenu() {
        
        pnlMenu.setSize(200, dtpModel.getHeight());
        
        for (Component c : pnlMenu.getComponents()) {
            
            if (c instanceof JButton b) {
                b.setSize(pnlMenu.getWidth(), pnlMenu.getHeight() / 12);
            }
            
            if (c instanceof JPanel p) {
                p.setSize(pnlMenu.getWidth(), pnlMenu.getHeight() / 12);
            }
        }
        
        connext.setForcus();
    }
    
    public void CloseMenu() {
        
        pnlMenu.setSize(78, dtpModel.getHeight());
        
        for (Component c : pnlMenu.getComponents()) {
            if (c instanceof JButton b) {
                b.setSize(78, pnlMenu.getHeight() / 12);
            }
            
            if (c instanceof JPanel p) {
                p.setSize(78, pnlMenu.getHeight() / 12);
            }
        }
    }
    
    public void hoverPanel(JPanel p) {
        
        p.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseEntered(MouseEvent e) {
                OpenMenu();
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                CloseMenu();
            }
        });
    }
    
    public void hoverButton(JButton b) {
        
        b.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseEntered(MouseEvent e) {
                OpenMenu();
            }
            
            @Override
            public void mouseClicked(MouseEvent e) {
                CloseMenu();
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                CloseMenu();
            }
        });
    }

    public void hoverPanelMenu() {
        for (Component comp : pnlMenu.getComponents()) {
            if (comp instanceof JButton b) {
                hoverButton(b);
            }
            
            if (comp instanceof JPanel p) {
                hoverPanel(p);
            }
        }
    }
    
}
